<section class="hero flex wrap">  
    <div class="hero-container flex wrap">
        <h1>Simon PATRY</h1>
        <div class="flex wrap">
            <p>I am <div class="parent"></div></p>
        </div>
    </div>
</section>
<section class="book">
    <div class="sewing">
        <div id="page1" class="page"></div>
        <div id="page2" class="page"></div>
        <div id="page3" class="page"></div>
    </div>
</section>
