<section class="log flex wrap">
	<form method="post" class="adminlog flex wrap">
		<p>
			<label for='identifiant'>Identifiant</label>
			<input type="text" name="identifiant" id="identifiant">
		</p>
		<p>
			<label for='pw'>Mot de passe</label>
			<input type="password" name="pw" id="pw">
		</p>
		<div class="flex ">
			<button id="adminform">Se connecter</button>
		</div>
		<p class="error"><?= $this-> message ?></p>
	</form>
</section>