<section>
    <h3>Projets</h3>
    <?php foreach($projects as $project): ?>
        <article data-name="form" data-id="<?= $project['id'] ?>" class="project hide">
            <form method="post" class="form" id="<?= $project['id'] ?>">
                <div>
                    <label for="name">Nom:</label>
                    <input class="name" name="name" id="name" value="<?= $project['name']?>">
                    <div class="text">
                        <label for="cat">Categorie:</label>
                        <select name="cat" class="cat" id="cat">
                            <option value="1">Web</option>
                            <option value="2">C#</option>
                            <option value="3">C</option>
                        </select>
                        <p>Description:</p>
                        <textarea class="desc"><?= $project['description']?></textarea>
                    </div>
                    <label for="img">Image:</label>
                    <input class="image" type="text" name="img" id="img" value="<?= $project['image']?>">
                    <label for="vid">video(embed):</label>
                    <input class="vid" type="text" name="vid" id="vid" value="<?= $project['video']?>">
                </div>
                <button type="button" data-id="<? $project['id'] ?>" class="save"><i class="fas fa-pen-nib">  Edit</i></button>
            </form>
        </article>
        <article id="<?= $project['name']?>" class="project flex wrap filter">
        
            <h3><?= $project['name']?></h3>
            
            <div class="text flex wrap">
                <div class="txt">
                    <div class="head">
                        <p>Categorie: <?= $project['category']?></p>
                        <p>Posté le: <?= $project['postDate']?></p>
                    </div>
                    <div class="description">
                        <p>Description:</p>
                        <hr>
                        <p><?= $project['description']?></p>    
                    </div>
                </div>
            </div>

            <div class="visual flex wrap">
                <div class="img">
                    <img src="<?= $project['image']?>" alt="preview <?= $project['name']?>">
                </div>
            <?php if($project['video'] != "" ): ?>
                <div class="vid responsive-video">
                    <iframe class="video" src="<?= $project['video']?>" title="<?= $project['name']?>" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            <?php endif; ?>
            </div>
            <div class="buttons flex wrap">
                <button data-id="<?= $project['id'] ?>" class="editProject"><i class="fas fa-pen-nib">  Edit</i></button>
                <button data-id="<?= $project['id'] ?>" class="delProject"><i class="fas fa-trash-alt"> Delete</i></button>
            </div>
        </article>
    <?php endforeach; ?>
    <article class="project filter">
        <h3>Nouveau projet:</h3>
        <form id="newProj" method="post" class="form" enctype="multipart/form-data">
            <div >
                <label for="name">Nom:</label>
                <input class="name" name="name">
                <div class="text">
                    <label for="cat">Categorie:</label>
                    <select name="cat">
                        <option value="1">Web</option>
                        <option value="2">C#</option>
                        <option value="3">C</option>
                    </select>
                    <label for="desc">Description:</label>
                    <textarea name="desc" id="desc" class="desc"></textarea>
                </div>
                <label for="image">Image</label>
                <input type="file" name="image" id="image" class="image-menus">
                <label for="video">video(embed):</label>
                <input class="vid" type="text" name="video" id="video">
                <button id="addProj" type="button" class="add"><i class="fas fa-pen-nib">ajouter</i></button>
            </div>
        </form>
    </article>
    <script src="assets/js/dashboard.js"></script>
</section>