
<?php foreach($projects as $project): ?>
    <article class="project flex wrap">
        <div class="txtImg flex wrap">
            <div class="text">
                <h3><?= $project['name']?></h3>
                <p>Categorie: <?= $project['category']?></p>
                <p>Posté le: <?= $project['postDate']?></p>
                <p>Description:</p>
                <p><?= $project['description']?></p>
            </div>
            <img src="<?= $project['image']?>" alt="preview <?= $project['name']?>">
        </div>
        <div class="video flex">
            <iframe src="https://www.youtube.com/embed/o_7J0Z2zRE4" title="<?= $project['name']?>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="buttons flex wrap">
            <button class="editProject"><i class="fas fa-pen-nib">  Edit</i></button>
            <button class="delProject"><i class="fas fa-trash-alt"> Delete</i></button>
        </div>
    </article>
<?php endforeach; ?>
