<section class="filter galleryArray">
    <h3>Gallerie</h3>
    <table id="dashboardGallery">
        <tr>
            <th>Project</th>
            <th>Src</th>
            <th>Alt</th>
            <th>Delete</th>
        </tr>
        <?php foreach($gallery as $image): ?>
        <tr>
            <?php foreach($projects as $project): ?>
                <?php if($project['id'] == $image['id_project']): ?>
                    <td><?=  htmlSpecialChars($project['name']) ?></td>
                <?php endif; ?>
            <?php endforeach; ?>
            <td><img  src="<?=  htmlSpecialChars($image['src']) ?>" alt="<?=  htmlSpecialChars($image['alt']) ?>"></td>
            <td><?=  htmlSpecialChars($image['alt']) ?></td>
            <td><a href="#" class="delImg" data-id="<?=  htmlSpecialChars($image['id']) ?>"><i class="fas fa-trash-alt"></i></a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</section>
<section class="filter galleryForm flex wrap">
    <h3>Nouvelle image</h3>
    <form method="post" enctype="multipart/form-data" id="newGallery">
    <ul>
        <li>
            <label for="src">Img:</label>
            <input class="src" name="src" id="src" type="file">
        </li>
        <li>
            <label for="alt">Alt:</label>
            <input class="alt" name="alt" id="alt" type="text">
        </li>
        <li>
            <label for="proj">Project:</label>
            <select id="proj" name="proj">
            <?php foreach($projects as $project): ?>
                <option value="<?=  htmlSpecialChars($project['id']) ?>"><?=  htmlSpecialChars($project['name']) ?></option>
            <?php endforeach; ?>
            </select>
        </li>
    </ul>
    <button id="addGallery">Ajouter</button>
    </form>
</section>
<script src="assets/js/dashboard.js"></script>