<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>CV simon</title>
        <meta name="description" content="Simon PATRY">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="assets/css/main.css" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
    	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
    </head>
    <body class="flex wrap">
    <video src="assets/ressources/images/bg-main.mov" autoplay loop playsinline muted></video>
    <header id="#top" class="flex wrap">
            <nav class="navbar">
                <ul class="navbar-nav">
                    <li class="logo">
                        <a href="accueil" class=" home">
                            <img src="assets/ressources/images/profil.jpg" alt="profil picture" class="profil">
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="accueil" class="nav-link">
                            <i class="fas fa-igloo fa-nav"></i>
                            <span class="link-text">HOME</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="" id="projects" class="nav-link">
                            <i class="fas fa-rocket fa-nav"></i>
                            <span class="link-text">PROJECTS</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="" id="categories" class="nav-link">
                            <i class="fas fa-clipboard-list fa-nav"></i>
                            <span class="link-text">CATEGORIES</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href=""  id="imgGallery" class="nav-link">
                            <i class="fas fa-image fa-nav"></i>
                            <span class="link-text">GALLERY</span>
                        </a>
                    </li>
                    <?php if(isset($_SESSION['admin'])): ?>
                    <li>
                        <a href="index.php?page=admin&action=deco" class="nav-link">
                            <i class="fas fa-ghost fa-nav"></i>
                            <span class="link-text">DECONNECTION</span>
                        </a>
                    </li>
                    <?php endif; ?>
                    <li class="nav-item" id="themeButton">
                        <a href="#top" class="nav-link">
                            <i class="fas fa-chevron-circle-up fa-nav"></i>
                            <span class="link-text">UP</span>
                        </a>
                    </li>
                    
                </ul>
            </nav>
        </header>
        <main class="dashMain">
            <section id="content" class="flex wrap">
                <h2>Infos persos:</h2>
                <form id="form" method="post" class="flex wrap">
                    <input id="firstname" value="<?=  htmlSpecialChars($contact['firstName']) ?>">
                    <input id="lastname" value="<?=  htmlSpecialChars($contact['lastName']) ?>">
                    <input id="mail" value="<?=  htmlSpecialChars($contact['mail']) ?>">
                    <input id="phone" value="<?=  htmlSpecialChars($contact['phone']) ?>">
                    <button id="updateContact" type="button">Update</button>
                </form>
            </section>
        </main>
        <script src="assets/js/dashboard.js"></script>
    </body>
</html>