<?php foreach($projects as $project): ?>
    <article data-name="form" data-id="<?= $project['id'] ?>" class="hide">
        <form method="post" class="form" id="<?= $project['id'] ?>">
            <div class="project">
                <label for="name">Nom:</label>
                <input class="name" name="name" value="<?= $project['name']?>"></input>
                <div class="text">
                    <label for="cat">Categorie:</label>
                    <select name="cat">
                        <option value="1">Web</option>
                        <option value="2">C#</option>
                        <option value="3">C</option>
                    </select>
                    <input class="cat" name="cat" type="text" value="<?= $project['category']?>"></input>
                    <p>Description:</p>
                    <textarea class="desc"><?= $project['description']?></textarea>
                </div>
                <label for="image">Image:</label>
                <input class="image" type="text" name="image" value="<?= $project['image']?>"></input>
                <label for="video">video(embed):</label>
                <input class="vid" type="text" name="video" value="<?= $project['video']?>"></input>
            </div>
            <button type="button" data-id="<? $project['id'] ?>" class="save"><i class="fas fa-pen-nib">  Edit</i></button>
        </form>
    </article>
    <article class="project flex wrap">
        <div class="txtImg flex wrap">
            <h3><?= $project['name']?></h3>
            <div class="text">
                <p>Categorie: <?= $project['category']?></p>
                <p>Posté le: <?= $project['postDate']?></p>
                <p>Description:</p>
                <p><?= $project['description']?></p>
            </div>
            <img src="<?= $project['image']?>" alt="preview <?= $project['name']?>">
        </div>
        <?php if($project['video'] != "" ): ?>
        <div class="video flex">
            <iframe src="<?= $project['video']?>" title="<?= $project['name']?>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <?php endif; ?>
        <div class="buttons flex wrap">
            <button data-id="<?= $project['id'] ?>" class="editProject"><i class="fas fa-pen-nib">  Edit</i></button>
            <button data-id="<?= $project['id'] ?>" class="delProject"><i class="fas fa-trash-alt"> Delete</i></button>
            <button class="img">add image</button>
        </div>
    </article>
<?php endforeach; ?>
<article>
        <form id="newProj" method="post" class="form" enctype="multipart/form-data">
            <div class="project">
                <label for="name">Nom:</label>
                <input class="name" name="name"></input>
                <div class="text">
                    <label for="cat">Categorie:</label>
                    <select name="cat">
                        <option value="1">Web</option>
                        <option value="2">C#</option>
                        <option value="3">C</option>
                    </select>
                    <label for="desc">Description:</label>
                    <textarea name="desc" class="desc"></textarea>
                </div>
                <label for="image">Image</label>
                <input type="file" name="image" class="image-menus"></input>
                <label for="video">video(embed):</label>
                <input class="vid" type="text" name="video"></input>
                <button id="addProj" type="button" class="add"><i class="fas fa-pen-nib">ajouter</i></button>
            </div>
        </form>
    </article>
    <script src="assets/js/dashboard.js"></script>