<table id="categoriesTab">
    <caption><strong>Gestion des Catégories</strong></caption>
    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>edit</th>
            <th>delete</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($categoriesTable as $category): ?>
        <tr data-id="1" class="hide" id="<?= $category['id'] ?>">
            <td><input class="id" type="text" value="<?=  htmlSpecialChars($category['id']) ?>"></td>
            <td><input class="name" type="text" value="<?=  htmlSpecialChars($category['name']) ?>"></td>
            <td><a href="#" class="editCat"><i class="fas fa-pen-nib"></i></a></td>
    	    <td><a><i class="fas fa-trash-alt"></i></a></td>
        </tr>
        <tr id="<?= $category['id'] ?>" >
            <td><?=  htmlSpecialChars($category['id']) ?></td>
            <td><?=  htmlSpecialChars($category['name']) ?></td>
            <td><a href="#" class="editCat" data-id="<?= $category['id'] ?>"><i class="fas fa-pen-nib"></i></a></td>
    	    <td><a href="#" class="delCat" data-id="<?= $category['id'] ?>"><i class="fas fa-trash-alt"></i></a></td>
        </tr>
    <?php endforeach;?>
    </tbody>  
    <tfoot>
        <tr id="addCat">
            <td><input id="catName" type="text"></td>
            <td><input id="is_dish" type="text"></td>
            <td><input id="description" type="text"></td>
            <td><a href="#" id="newCat">Add Category</a></td>
        </tr>
     </tfoot> 
</table>