<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>CV simon</title>
        <meta name="description" content="Simon PATRY">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="assets/css/main.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    </head>
    <body class="flex wrap">
        <header id="#top" class="flex wrap">
            <div class="flex wrap">
                <a href="index.php" class="home"><img src="assets/images/profil.jpg" alt="profil picture" class="profil"></a>
                <a class="login" href="index.php?page=admin"><h1>Simon PATRY</h1></a>
            </div>
            <nav class="flex wrap">
                <div class="menu">
                    <ul>
                        <li><a href="#hero" >Home</a></li>
                        <li><a href="#about" >About</a></li>
                        <li><a href="#resume" >Resume</a></li>
                        <li><a href="#portfolio">Portfolio</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
            </nav>
        </header>
        <main>
            <section>
                <?php include $template ?>
            </section>
        </main>
    </body>
    <script src="assets/js/main.js"></script>
    <script src="assets/js/heroContainer.js"></script>
    <script src="assets/js/turnPage.js"></script>
</html>