<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>CV simon</title>
        <meta name="description" content="Simon PATRY">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="assets/css/main.css" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
    	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
    </head>
    <body>
    <video src="assets/ressources/images/bg-main.mov" autoplay loop playsinline muted></video>
        <header id="#top" class="flex wrap">
            <nav class="navbar">
                <ul class="navbar-nav">
                    <li class="logo">
                        <a href="accueil" class=" home">
                            <img src="assets/ressources/images/profil.jpg" alt="profil picture" class="profil">
                        </a>
                    </li>
                    <li class="name nav-item">    
                        <?php if(isset($_SESSION['admin'])): ?>
                        <a class="login nav-link" href="dashboard">
                            <i class="fas fa-flushed fa-nav"></i>
                            <span class="name link-text">SIMON PATRY</span>
                        </a>
                        <?php else: ?>
                        <a class="login nav-link" href="admin">
                            <i class="fas fa-flushed fa-nav"></i>
                            <span class="link-text">SIMON PATRY</span>
                        </a>
                        <?php endif; ?>
                    </li>
                    <li class="nav-item">
                        <a href="accueil" class="nav-link">
                            <i class="fas fa-igloo fa-nav"></i>
                            <span class="link-text">HOME</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="portfolio" class="nav-link">
                            <i class="fas fa-dungeon fa-nav"></i>
                            <span class="link-text">PORTFOLIO</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="cv" class="nav-link">
                            <i class="fas fa-id-badge fa-nav"></i>
                            <span class="link-text">CV</span>
                        </a>
                    </li>
                    <?php if(isset($_SESSION['admin'])): ?>
                    <li>
                        <a href="index.php?page=admin&action=deco" class="nav-link">
                            <i class="fas fa-ghost fa-nav"></i>
                            <span class="link-text">DECONNECTION</span>
                        </a>
                    </li>
                    <?php endif; ?>
                    <li class="nav-item" id="themeButton">
                        <a href="#top" class="nav-link">
                            <i class="fas fa-chevron-circle-up fa-nav"></i>
                            <span class="link-text">UP</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </header>
        <main>
            <div class=" template flex wrap">
                <?php include $template ?>
            </div>
        </main>
        <script src="assets/js/main.js"></script>
        <script src="assets/js/heroContainer.js"></script>
        <script src="assets/js/slider.js"></script>
    </body>
</html>