<?php foreach($projects as $project): ?>
    <article id="<?= $project['name']?>" class="project flex wrap filter">
        
        <h3><?= $project['name']?></h3>
        
        <div class="text flex wrap">
            <div class="txt">
                <div class="head">
                    <p>Categorie: <?= $project['category']?></p>
                    <p>Posté le: <?= $project['postDate']?></p>
                </div>
                <div class="description">
                    <p>Description:</p>
                    <hr>
                    <p><?= $project['description']?></p>    
                </div>
            </div>
        </div>

        <div class="visual flex wrap">
            <div class="img">
                <img src="<?= $project['image']?>" alt="preview <?= $project['name']?>">
            </div>
        <?php if($project['video'] != "" ): ?>
            <div class="vid responsive-video">
                <iframe class="video" src="<?= $project['video']?>" title="<?= $project['name']?>" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        <?php endif; ?>
        </div>

        <div class="gallery flex">
            <button class="previous" data-id="<?= $project['name']=preg_replace('/ /', '', $project['name']) ?>"><i class="fas fa-arrow-circle-left"></i></button>
            <div class="slider flex wrap">
                
                <?php foreach($gallery as $image): ?>
                    <?php if($image['id_project'] == $project['id']): ?>
                        <div class="sliderImage gall<?= $project['name']=preg_replace('/ /', '', $project['name']) ?> flex">
                            <img src="<?= $image['src'] ?>" alt ="<?= $image['alt'] ?>">
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                
            </div>
            <button class="next" data-id="<?= $project['name']=preg_replace('/ /', '', $project['name']) ?>"><i class="fas fa-arrow-circle-right"></i></button>
        </div>
    </article>

<?php endforeach; ?>