<?php foreach($projects as $project): ?>
    <article class="project flex wrap">
            <div class="txtImg flex wrap">
                <h3><?= $project['name']?></h3>
                <div class="text">
                    <p>Categorie: <?= $project['category']?></p>
                    <p>Posté le: <?= $project['postDate']?></p>
                    <p>Description:</p>
                    <p><?= $project['description']?></p>
                </div>
                <img src="<?= $project['image']?>" alt="preview <?= $project['name']?>">
            </div>
            <div class="video flex">
                <iframe src="<?= $project['video']?>" title="<?= $project['name']?>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
    </article>
<?php endforeach; ?>